t1 = input('BTCUSDT', type=input.symbol)
t2 = input('ETHUSDT', type=input.symbol)
t3 = input('XRPUSDT', type=input.symbol)

strategy() =>
    smaFast = ta.sma(close, 50)
    smaSlow = ta.sma(close, 200)
    goLong = ta.crossover(smaFast, smaSlow)
    goShort = ta.crossunder(smaFast, smaSlow)
    goLong := true
    signal = goLong ? 1 : goShort ? -1 : 0  

screener = (_ticker) =>
    message = ''
    [signal, tickerClose] = security(_ticker, timeframe.period, [strategy(), close])
    if signal == 1
        message := 'Long'
    else if signal == -1
        message := 'Short'

    if signal == 1 or signal == -1
        alert(message, alert.freq_once_per_bar_close)

    signal

t1_signal = screener(t1)
t2_signal = screener(t2)
t3_signal = screener(t3)

plot(t1_signal, color=color.green, title='t1')
plot(t2_signal, color=color.blue, title='t2')
plot(t3_signal, color=color.red, title='t3')